name: issueblogger

on:
  issues:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Keeping this to handle the submodule

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # or any other compatible Python version

      - name: Install Dependencies
        run: pip install -r scripts/requirements.txt  # Assuming your dependencies are listed here

      - name: Fetch Issue Data
        run: |
          curl "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" > issue_details.json
          curl "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" > issue_comments.json
          echo '{"issue_data":' > issue_data.json
          cat issue_details.json >> issue_data.json
          echo ',"comments":' >> issue_data.json
          cat issue_comments.json >> issue_data.json
          echo '}' >> issue_data.json

      - name: Generate Content
        run: python scripts/issueblogger.py issue_data.json  # Adjust path as needed

      - name: Commit and Push Changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git fetch
          git checkout main
          git pull origin main
          BRANCH_NAME="${{ github.event.issue.number }}-issueblogger"
          git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"
          git add ./blog/${{ github.event.issue.number }}-new-post.md
          git commit -m "Add new blog post for issue #${{ github.event.issue.number }}"
          git push -u origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          branch: ${{ github.event.issue.number }}-issueblogger
          base: main
          title: "New Blog Post: Issue #${{ github.event.issue.number }}"
          body: "This pull request contains the blog post content for Issue #${{ github.event.issue.number }}."
