name: issueblogger

on:
  issues:
    types: [closed]

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r scripts/requirements.txt

      - name: Fetch Issue Data and Generate Content
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/issueblogger.py ${{ github.event.issue.number }}

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git checkout main
          git pull

          BRANCH_NAME="${{ github.event.issue.number }}-issueblogger"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Add new blog post for issue #${{ github.event.issue.number }}"
          git push --force --set-upstream origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ secrets.GH_PAT }}
          base: main
          branch: ${{ github.event.issue.number }}-issueblogger
          title: "New Blog Post: Issue #${{ github.event.issue.number }}"
          body: "This pull request contains the blog post content for Issue #${{ github.event.issue.number }}."
