name: issueblogger

on:
  issues:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # or any other compatible Python version

      - name: Install Dependencies
        run: |
          pip install -r scripts/requirements.txt  # Assuming your dependencies are listed here

      - name: Fetch Issue Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch Issue Details
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" > issue_details.json
          
          # Fetch Comments
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" > issue_comments.json

          # Combine issue details and comments into one file
          echo '{"issue_data":' > issue_data.json
          cat issue_details.json >> issue_data.json
          echo ',"comments":' >> issue_data.json
          cat issue_comments.json >> issue_data.json
          echo '}' >> issue_data.json

      - name: Generate Content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/issueblogger.py issue_data.json  # Adjust path as needed
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          
          # Set the remote URL to use HTTPS
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          git checkout main

          git fetch
          git pull
          
          # Create a new branch and commit changes
          BRANCH_NAME="${{ github.event.issue.number }}-issueblogger"
          git checkout -b "$BRANCH_NAME" main
          git add ./blog/${{ github.event.issue.number }}-new-post.md
          git commit -m "Add new blog post for issue #${{ github.event.issue.number }}"

          # Push the branch to the remote repository
          git push -u origin "$BRANCH_NAME"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add new blog post for issue #${{ github.event.issue.number }}"
          title: "Blog Post: ${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          branch: "${{ github.event.issue.number }}-issueblogger" # The new branch with changes
          base: "main" # The branch you want to merge into

      - name: Check PR Output
        if: always()
        run: |
          echo "PR Number: ${{ steps.create_pr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.create_pr.outputs.pull-request-url }}"

