name: run llmjob

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  issues: write

jobs:
  solve-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'llmjob'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Update submodules to tracked branch
        run: git submodule update --remote

      - name: Sanity check
        run: cat ./scripts/llmjob.sh

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r scripts/requirements.txt

      - name: Execute Solver Script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: bash ./scripts/llmjob.sh ${{ github.event.issue.number }}

