name: update submodules

on:
  push:
    branches:
      - scripts
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout Submodule
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update submodule to latest commit on its main branch
        run: |
          cd scripts  # Replace with the path to your submodule
          git fetch
          git checkout origin/scripts  # Replace with the branch you want to track
          git pull origin scripts      # Replace with the branch you want to track
          cd ../
          git add scripts
          git commit -m "Update submodule to latest commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
